# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'DocumentManagerProject' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for DocumentManagerProject
  pod 'Zip', '~> 1.0'

  target 'DocumentManagerProjectTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'DocumentManagerProjectUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
